language: python

sudo: false

addons:
  apt:
    sources:
      - mopidy-stable
    packages:
      - libffi-dev
      - libspotify-dev
      - libspotify12
      - portaudio19-dev

matrix:
  include:
    - python: 3.3
      env:
        - TOX_ENV=py33
    - python: 3.4
      env:
        - TOX_ENV=py34
    - python: 3.5
      env:
        - TOX_ENV=py35
    - python: 3.5
      env:
        - TOX_ENV=flake8

install:
  - pip install tox
  - pip install coveralls

script:
  - tox -e $TOX_ENV

after_success: coveralls
