language: python

sudo: false

addons:
  apt:
    sources:
      - mopidy-stable
    packages:
      - libffi-dev
      - libspotify-dev
      - libspotify12
      - portaudio19-dev

env:
    - TOX_ENV=py33
    - TOX_ENV=py34
    - TOX_ENV=flake8

install:
    - pip install tox
    - pip install coveralls

script:
    - tox -e $TOX_ENV

after_success:
    coveralls
