language: node_js

sudo: false

node_js:
  - 4.0
  - 4.1
  - 4.2
  - 5.0
  - 5.1
  - 5.2
  - 5.3
  - 5.4

install:
  - npm install
  - npm install coveralls
  - npm install mocha-lcov-reporter

script:
  - gulp test

after_success:
  - coveralls
